name: ServerPlugin
author: Neon
version: 1.0
main: de.neon.serverplugin.ServerPlugin
depend: [DeluxeChat,Vault]
commands:
  duel:
    aliases: [d]
    discription: Duel with someone.
    usage: </duel>
  stats:
    discription: View/Skill your stats.
    usage: </stats>
  teleport:
    discription: Teleport yourself.
    aliases: [tp]
    usage: </teleport> (Player1)
  teleporthere:
    discription: Teleport someone to you.
    aliases: [tphere, tph]
    usage: </teleporthere> (Player1)